### ISSUE TITLE
Calling task.delay() blocks

### ISSUE THREAD

**Issue by Djayb6** [SentimensRG/txCelery#1]
Hello, 

When I call a task wrapped by CeleryClient with .delay(), the DeferredTask is not returned until the task has completed, which seems to defeat the entire purpose of txCelery. I added some debug prints, and it appears that _monitor_task is called continuously until the task has completed.

**Comment by lthibault** [comment]
Hello,

I'm sorry, but we're no longer developing txCelery, so this bug is unlikely to be fixed in the near future.  If you have a fix, I'll gladly merge it (and add you as a contributor, if you'd like to maintain the project).

**Comment by Djayb6** [comment]
Hello Louis,

Could we talk on Skype ? I am interested to contribute to this project but I have some questions about the code. 

My Skype ID is jbperaldi

See you.

Envoyé de mon iPhone

**Comment by lthibault** [comment]
@Djayb6 

I'll very gladly answer questions about code, but since the code is to remain open-source, let's use the issue tracker.  Please open a separate issue and ask your questions there, and I'll help get you working on the code.

Regards,

**Comment by jarrodchesney** [comment]
This is blocking for me too

I've forked and applied a fix that seems to work.

I'm not sure how the cancelling is supposed to work at this stage.

**Comment by tshabs** [comment]
Hi, your fork is working well for me.  Thanks :)

Maybe you should create a PR.

@lthibault i would be happy to assist with maintaining this project as I am using it in a few projects now.  I'm not an expert with twisted but am learning.

**Comment by jarrodchesney** [comment]
At that point i was just playing with it. When we move to using Celery, I'll go over it again and submit a PR.

**Comment by lthibault** [comment]
Hi guys,

Glad it's working for you.  Let me know if I can do anything to move the PR along.

**Comment by lthibault** [comment]
@tshabs Any help is most welcome.  Feel free to buzz if you need anything.

**Comment by slav0nic** [comment]
any updates?
new celery have some improvements that can be use with twisted (i hope): http://docs.celeryproject.org/en/stable/whatsnew-4.0.html#asyncresult-then-on-success-on-error

**Comment by jarrodchesney** [comment]
You can just have

d = Deferred()
add.delay(2, 2).then(d.callback, lambda e: d.errback(Failure(e))

# Then use the deferred like normal, return, it or whatever

d.addCallback(lambda v:print(v))

On 7 Nov. 2016, at 7:28 pm, Sergey Maranchuk <notifications@github.com<mailto:notifications@github.com>> wrote:

any updates?
new celery have some improvements that can be use with twisted (i hope): http://docs.celeryproject.org/en/stable/whatsnew-4.0.html#asyncresult-then-on-success-on-error

**Comment by slav0nic** [comment]
yep, tnx @jarrodchesney but will be fine have some decorator for celery task that allow use this in `inlineCallbacks` without defining `Deferred`, callback/errorback, etc
