### ISSUE TITLE
Understanding of the DeferredTask class

### ISSUE THREAD

**Issue by Djayb6** [SentimensRG/txCelery#2]
Hello,

During the creation of DeferredTask, the `_monitor_task` method is called once. This method will `yield` as long as the task status is PENDING. How this construction can be asynchronous ? Currently this blocks the current thread until the task is finished.

**Comment by clokep** [comment]
My understanding of how this works is that the `yield` gives control back to the reactor such that any other tasks the reactor is waiting to process can be taken care of. Eventually the reactor will come back into the `DeferredTask`'s  `while` loop and check the value of `async_result.state` again. I've been using this code for a while now and it's definitely async. :smile:

**Comment by Djayb6** [comment]
Hello clokep ! Would you be able to show me some code ? I've never been able to get it to work

**Comment by lthibault** [comment]
@Djayb6  Please consider this repository to be unsupported, defunct and hopelessly broken.

**Comment by clokep** [comment]
The example code in the README works pretty well, although I usually use `DeferredTask` directly:

``` python
# Your celery "app" object.
from celery import app
from txcelery.defer import DeferredTask
from twisted.internet import defer

# Inline callbacks are easier, but you should be able to use addCallback also.
@defer.inlineCallbacks
def some_async_call():
    # Wait for a task to finish.
    task = celery.send_task('your_app.tasks.whatever', args=[some, args])
    yield DeferredTask(task)

    # Or if you can import the task directly.
    from your_app.tasks import whatever
    task = whatever.delay(some, args)
    yield DeferredTask(task)
```

Hope that helps!

**Comment by clokep** [comment]
@lthibault said:

> @clokep Please consider this repository to be unsupported, defunct and hopelessly broken.

I saw you said it's unsupported, is there a known reason that this is 'broken'? That would be great to document for people!

**Comment by lthibault** [comment]
@clokep Firstly, I meant to mention Djayb6 -- sorry about that!

Secondly, I truly and honestly forgot about our previous exchange... _mea culpa_.  If you got it to work, then I rescind the "hopelessly broken" bit.

In any case, apologies!
