### ISSUE TITLE
Decorator class name doesn't suggest it's purpose

### ISSUE THREAD

**Issue by jarrodchesney** [SentimensRG/txCelery#5]
The decorator class @CeleryClient is a rather generic name. It does not indicated that it's related to twisted or deferreds at all.

I propose renaming it to DeferrableTask, Wrapping a task in deferrable tasks returns a DeferredTask.
Leaving an alias for CeleryClient is a must.

**Comment by lthibault** [comment]
Merged.  Thanks for your contribution!
